### ISSUE TITLE
In the last week, a lot of pages with the history of different sites began to open with "error".

### ISSUE THREAD

**Issue by vitalii2011** [maxlath/website-history-browser#2]
![Image 001](https://user-images.githubusercontent.com/41552153/187062678-586e005f-1f1e-4e14-897e-029537ae4da8.png)

**Comment by maxlath** [comment]
which version of Firefox and of the addon are you using?

**Comment by maxlath** [comment]
never mind: I updated to Firefox 104.0 and now get the same error ><

**Comment by vitalii2011** [comment]
> which version of Firefox and of the addon are you using?

Firefox 104.0, Website History Browser 1.1.4.

**Comment by maxlath** [comment]
That should now be fixed in v1.1.5 (patch: f666276). Can you try updating the addon and confirm?

**Comment by vitalii2011** [comment]
> That should now be fixed in v1.1.5 (patch: [f666276](https://github.com/maxlath/website-history-browser/commit/f666276dea2d348227755f30c38b3ab2440d47d0)). Can you try updating the addon and confirm?

Yes, I confirm - in 1.1.5 of the above problems, on the sites used for verification - no. Thanks a lot!
